# Generated by Django 3.0.2 on 2020-01-11 20:48

import datetime
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('birds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('activity', models.CharField(blank=True, choices=[('', ''), ('orokonui', 'Visiting Orokonui'), ('tourist', 'Tourist'), ('local', 'Local'), ('school', 'School Group'), ('community', 'Community Group'), ('skier', 'Skier'), ('tramper', 'Tramper'), ('hunter', 'Hunter'), ('birder', 'Birder'), ('doc', 'DOC Staff'), ('research', 'Researcher'), ('other', 'Other')], default='', max_length=15)),
                ('heard', models.CharField(blank=True, choices=[('', ''), ('orokonui', 'Orokonui Ecosanctuary'), ('poster', 'Poster'), ('brochure', 'Brochure'), ('social', 'Social Media'), ('news', 'News'), ('friend', 'From a friend'), ('other', 'Other')], default='', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sighted', models.DateField(validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date.today)])),
                ('time_sighted', models.TimeField()),
                ('observation_type', models.CharField(choices=[('sighted', 'Sighted'), ('heard', 'Heard'), ('distant', 'Sighted (distant)')], max_length=15)),
                ('point_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('precision', models.PositiveIntegerField(choices=[(10, '(10m) GPS Coordinates'), (50, '(50m) Known Location'), (200, '(200m) Approximate Location'), (1000, '(1000m) General Area'), (5000, '(5000m) Educated Guess')])),
                ('number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('new', 'New'), ('public', 'Verified (Public)'), ('Private', (('private', 'Verified (Private)'), ('bad', 'Bad (Private)'))), ('Special', (('captive', 'Captive Sighting'),))], default='new', help_text='Moderator: confirm verification and private/public status', max_length=10)),
                ('favourite', models.BooleanField(default=False, help_text='Moderator: If noteworthy observation')),
                ('confirmed', models.BooleanField(default=False, help_text='Moderator: If confirmed (known contributor or photo evidence)')),
                ('moderator_notes', models.TextField(blank=True, help_text='Moderator: Add notes here if you needed to change observation information (not public).')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('comments', models.TextField(blank=True)),
                ('location_details', models.TextField(blank=True)),
                ('behaviour', models.TextField(blank=True)),
                ('geocode', models.CharField(blank=True, max_length=200, null=True)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('contributor', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='observations.Contributor')),
            ],
            options={
                'ordering': ['-date_sighted', '-time_sighted'],
            },
        ),
        migrations.CreateModel(
            name='BirdObservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banded', models.CharField(choices=[('unknown', "Couldn't tell"), ('unreadable', 'Banded, unreadable'), ('readable', 'Banded, readable'), ('unbanded', 'Not banded')], max_length=15)),
                ('band_combo', models.CharField(blank=True, max_length=200, null=True)),
                ('sex_guess', models.CharField(blank=True, choices=[('', 'Unsure'), ('female', 'Female'), ('male', 'Male')], max_length=15, null=True)),
                ('life_stage_guess', models.CharField(blank=True, choices=[('', 'Unsure'), ('fledgling', 'Fledgling'), ('juvenile', 'Juvenile'), ('sub-adult', 'Sub-Adult'), ('adult', 'Adult')], max_length=15, null=True)),
                ('revisit', models.BooleanField(default=False, help_text='Moderator: tick if bird not added yet')),
                ('bird', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='birds.Bird')),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birds', to='observations.Observation')),
            ],
        ),
    ]
