# Generated by Django 3.0.2 on 2020-01-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birdobservation',
            name='life_stage_guess',
            field=models.CharField(blank=True, choices=[('', 'Undetermined'), ('fledgling', 'Fledgling'), ('juvenile', 'Juvenile'), ('sub-adult', 'Sub Adult'), ('adult', 'Adult')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='birdobservation',
            name='sex_guess',
            field=models.CharField(blank=True, choices=[('', 'Unsure/Unknown'), ('female', 'Female'), ('male', 'Male')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='activity',
            field=models.CharField(blank=True, choices=[('', ''), ('orokonui', 'Visiting Orokonui'), ('tourist', 'Tourist'), ('local', 'Local'), ('school', 'School Group'), ('community', 'Community Group'), ('tramper', 'Tramper'), ('hunter', 'Hunter'), ('birder', 'Birder'), ('doc', 'DOC Staff'), ('research', 'Researcher'), ('other', 'Other')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='observation',
            name='moderator_notes',
            field=models.TextField(blank=True, help_text='Moderator: Add notes here (non-public) if desired'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='precision',
            field=models.PositiveIntegerField(choices=[(10, '(10m) GPS Coordinates'), (50, '(50m) Known Location'), (200, '(200m) Approximate Location'), (1000, '(1000m) General Area')]),
        ),
        migrations.AlterField(
            model_name='observation',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('public', 'Verified (Public)'), ('private', 'Verified (Private)'), ('invalid', 'Invalid (Private)'), ('captive', 'Captive (Special)')], default='new', help_text='Moderator: confirm verification and private/public status', max_length=10),
        ),
    ]
