# Generated by Django 3.0.2 on 2020-01-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0002_auto_20200114_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='activity',
            field=models.CharField(blank=True, choices=[('', ''), ('ecosanctuary', 'Visiting an Ecosanctuary'), ('tourist', 'Tourist'), ('local', 'Local'), ('school', 'School Group'), ('community', 'Community Group'), ('tramper', 'Tramper'), ('hunter', 'Hunter'), ('birder', 'Birder'), ('doc', 'DOC Staff'), ('research', 'Researcher'), ('other', 'Other')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='heard',
            field=models.CharField(blank=True, choices=[('', ''), ('ecosanctuary', 'Ecosanctuary'), ('poster', 'Poster'), ('brochure', 'Brochure'), ('social', 'Social Media'), ('news', 'News'), ('friend', 'From a friend'), ('other', 'Other')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='observation',
            name='precision',
            field=models.PositiveIntegerField(choices=[(100, 'Known Location (100m)'), (250, 'Approximate Location (250m)'), (1000, 'General Area (1000m)')]),
        ),
    ]
