# Generated by Django 3.0 on 2019-12-17 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('birds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandCombo',
            fields=[
                ('bird', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='band_combo', serialize=False, to='birds.Bird')),
                ('combo', models.CharField(max_length=255)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['bird'],
            },
        ),
    ]
