# Generated by Django 3.0.2 on 2020-01-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bird',
            name='sex',
            field=models.CharField(blank=True, choices=[('', 'Unsure/Unknown'), ('female', 'Female'), ('male', 'Male')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='bird',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bird',
            name='status',
            field=models.CharField(blank=True, choices=[('', 'Unknown'), ('alive', 'Alive'), ('dead', 'Dead')], default='', max_length=15),
        ),
    ]
