# Generated by Django 3.0.2 on 2020-01-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0003_birdprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bird',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True),
        ),
    ]
