# Generated by Django 3.0.2 on 2020-01-14 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0004_auto_20200115_0211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='birdprofile',
            old_name='profile_picture',
            new_name='picture',
        ),
        migrations.RenameField(
            model_name='birdprofile',
            old_name='profile_picture_attribution',
            new_name='picture_attribution',
        ),
        migrations.RenameField(
            model_name='birdprofile',
            old_name='profile_picture_ppoi',
            new_name='picture_ppoi',
        ),
        migrations.AlterField(
            model_name='birdprofile',
            name='bird',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='birds.Bird'),
        ),
    ]
